---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
- name: server1
  #image: geerlingguy/docker-debian13-ansible:latest
  image: debian:speed 
  command: /sbin/init
  cgroupns_mode: host
  memory: 2046M
  cpu: 1
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  groups:
  - servers
  - test_hosts
  networks:
  - name: molec-net
    aliases: ["server1"]
- name: server2
  #image: geerlingguy/docker-debian13-ansible:latest
  image: debian:speed 
  command: /sbin/init
  cgroupns_mode: host
  memory: 2046M
  cpu: 1
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  groups:
  - servers
  - test_hosts
  networks:
  - name: molec-net
    aliases: ["server2"]
- name: client1
  #image: geerlingguy/docker-debian13-ansible:latest
  image: debian:speed 
  command: /sbin/init
  cgroupns_mode: host
  memory: 2046M
  cpu: 1
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  groups:
  - clients
  - test_hosts
  networks:
  - name: molec-net
    aliases: ["client1"]
- name: client2
  #image: geerlingguy/docker-debian13-ansible:latest
  image: debian:speed 
  command: /sbin/init
  cgroupns_mode: host
  memory: 2046M
  cpu: 1
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  groups:
  - clients
  - test_hosts
  networks:
  - name: molec-net
    aliases: ["client2"]

provisioner:
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      servers:
        iperf3_server_instances:
          - 5201
    host_vars:
      server1:
        test_ip: "{{inventory_hostname}}"
        id: 1
      server2:
        test_ip: "{{inventory_hostname}}"
        id: 2
      client1:
        test_ip: "{{inventory_hostname}}"
        id: 3
        iperf3_client_instances:
          - name: to-server1
            target: server1
            port: 5201
      client2:
        test_ip: "{{inventory_hostname}}"
        id: 4
        iperf3_client_instances:
          - name: to-server2
            target: server2
            port: 5201

verifier:
  name: ansible
