---
- name: Install iperf3
  ansible.builtin.package:
    name: "{{ iperf3_server_package }}"
    state: present
  become: true

- name: Ensure iperf3 system user exists
  ansible.builtin.user:
    name: iperf3
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    home: /nonexistent
  become: true

- name: Deploy iperf3 systemd template
  ansible.builtin.template:
    src: iperf3@.service.j2
    dest: "/etc/systemd/system/iperf3{{ iperf_base_prefix }}@.service"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload systemd

- name: Enable iperf3 server instances
  ansible.builtin.systemd:
    name: "iperf3{{ iperf_base_prefix }}@{{ item }}"
    enabled: true
    state: started
  loop: "{{ iperf3_server_instances }}"
  when: iperf3_server_instances | length > 0
  become: true
