---
- name: Install iperf3
  ansible.builtin.package:
    name: "{{ iperf3_server_package }}"
    state: present
  become: true

- name: Deploy iperf3 systemd template
  ansible.builtin.template:
    src: iperf3@.service.j2
    dest: /etc/systemd/system/iperf3@.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload systemd

- name: Enable iperf3 server instances
  ansible.builtin.systemd:
    name: "iperf3@{{ item }}"
    enabled: true
    state: started
  loop: "{{ iperf3_server_instances }}"
  when: iperf3_server_instances | length > 0
  become: true
